### ISSUE TITLE
chrome for os x not need this

### ISSUE THREAD

**Issue by 499978920** [galambalazs/smoothscroll#116] opened 2015-09-20 11:05 UTC
I use os x and win. this plugin is not necessary for os x,can you modify it to ignore for os x?

**Comment by galambalazs** [comment] 2015-09-20 11:34
Chrome for OS X does need it (using your mouse wheel). 

What you may refer to is Touchpad scrolling. Did you try to disable that feature?

**Comment by galambalazs** [comment] 2015-09-20 11:38
duplicate of https://github.com/galambalazs/smoothscroll/issues/65

**Closed by galambalazs** 2015-09-20 11:38 UTC
